ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS notify_tasks BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notify_messages BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS presence_hidden BOOLEAN NOT NULL DEFAULT false;